require('plugin_configs.lualine')
-- require('plugin_configs.nvim-tree')
require('plugin_configs.treesitter')
require('plugin_configs.telescope')
require('plugin_configs.coc_config')
require('plugin_configs.skeletons')
-- require('plugin_configs.lsp_config')
